### PR TITLE
Add support for FreeBSD

### LINKED ISSUE #14: Add support for FreeBSD
Support for FreeBSD is lacking in this formula, and `map.jinja` doesn't seem to allow a way to slime it in via pillar lookup, unless you're running a very old Salt.

### PR DESCRIPTION
**Pull request by tnalpgge**
Also permit pillar lookups for recent Salt versions, in case of other unknown operating systems.
Fix #14

### CODE REVIEW

**Comment by marco-m** [comment]
Hello, any news?

**Comment by javierbertoli** [comment]
There are some conflicts on `dnsmasq/map.jinja` file. @tnalpgge can you fix it?

**Comment by tnalpgge** [comment]
Conflicts resolved, available for review again.

**Comment by aboe76** [comment]
thanks for al this testing and quick fixes.

**Pull request merged**
